rust: update to 1.90.0, closes #35

diff --git a/rust/Pkgfile b/rust/Pkgfile
--- a/rust/Pkgfile
+++ b/rust/Pkgfile
@@ -6,9 +6,9 @@
 # Optional: clang libgit2 polly sccache
 
 name=rust
-version=1.89.0
-_date=2025-06-26
-_rustc=1.88.0
+version=1.90.0
+_date=2025-08-07
+_rustc=1.89.0
 _cargo=$_rustc
 release=1
 
@@ -19,7 +19,10 @@ source=(https://static.rust-lang.org/dist/${name}c-$version-src.tar.xz
   0001-bootstrap-Change-libexec-dir.patch
   0002-bootstrap-Change-bash-completion-dir.patch
   0003-compiler-Change-LLVM-targets.patch
-  0004-compiler-Use-wasm-ld-for-wasm-targets.patch)
+  0004-compiler-Use-wasm-ld-for-wasm-targets.patch
+  0006-compiler-Swap-primary-and-secondary-lib-dirs.patch
+  0007-bootstrap-Workaround-for-system-stage0.patch
+)
 
 unpack_source() {
 	for file in ${source[@]}; do
@@ -68,50 +71,44 @@ build() {
 	patch -p1 -i $SRC/0002-bootstrap-Change-bash-completion-dir.patch
 	patch -p1 -i $SRC/0003-compiler-Change-LLVM-targets.patch
 	patch -p1 -i $SRC/0004-compiler-Use-wasm-ld-for-wasm-targets.patch
+  patch -p1 -i $SRC/0006-compiler-Swap-primary-and-secondary-lib-dirs.patch
+  patch -p1 -i $SRC/0007-bootstrap-Workaround-for-system-stage0.patch
 
 cat <<- EOF > $SRC/bootstrap.toml
 profile = "dist"
-change-id = 142379
+change-id = 144675
 
 [llvm]
-ninja = true
-link-shared = true
 download-ci-llvm = false
-@POLLY@
 
 [install]
 prefix = "/usr"
 
 [rust]
-# LLVM crashes when passing an object through ThinLTO twice.  This is triggered
-# when using rust code in cross-language LTO if libstd was built using ThinLTO.
-# http://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html
-# https://github.com/rust-lang/rust/issues/54872
 channel = "stable"
 codegen-units = 1
 codegen-units-std = 1
 debuginfo-level = 1
 debuginfo-level-std = 2
+debug-assertions = false
+remap-debuginfo = false
 codegen-tests = false
 backtrace-on-ice = true
+lld = false
+use-lld = "external"
+llvm-bitcode-linker = false
 jemalloc = true
-remap-debuginfo = false
-debug-assertions = false
 
 rpath = false
 frame-pointers = true
 deny-warnings = false
-optimize = true
-codegen-backends = ["llvm"]
-lld = false
-use-lld = false
 lto = "off"
 
 [build]
 target = ["armv7-unknown-linux-gnueabihf"]
 description = "CRUX"
 tools = ["cargo",
- "clippy",
+  "clippy",
   "rustfmt",
   "analysis",
   "src",
@@ -128,17 +125,53 @@ vendor = true
 locked-deps = true
 python = "/usr/bin/python3"
 optimized-compiler-builtins = true
+#@CARGO@
+#@RUST@
+#@RUSTFMT@
+
+[dist]
+compression-formats = ["gz"]
+compression-profile = "fast"
 
 [target.armv7-unknown-linux-gnueabihf]
 llvm-config = "/usr/bin/llvm-config"
 llvm-filecheck = "/usr/bin/FileCheck"
-cc = "/usr/bin/gcc"
-cxx = "/usr/bin/g++"
-ar = "/usr/bin/gcc-ar"
-ranlib = "/usr/bin/gcc-ranlib"
+cc = @TARGETCC@
+cxx = @TARGETCXX@
+ar = @TARGETAR@
+ranlib = @TARGETRANLIB@
 EOF
 
-    prt-get isinst polly && sed -e 's|@POLLY@|polly = true|' -i $SRC/bootstrap.toml || sed -e 's|@POLLY@||' -i $SRC/bootstrap.toml
+    if [ -e '/usr/bin/rustc' ]; then
+        if ! /usr/bin/ldd /usr/bin/rustc /usr/bin/cargo | grep -q -E '.*not found'; then
+            sed -e 's|@CARGO@|cargo = "/usr/bin/cargo"|' \
+              -e 's|@RUST@|rustc = "/usr/bin/rustc"|' \
+              -e 's|@RUSTFMT@|rustfmt = "/usr/bin/rustfmt"|' \
+              -i $SRC/bootstrap.toml
+        else
+            sed -e 's|@CARGO@||' \
+              -e 's|@RUST@||' \
+              -e 's|@RUSTFMT@||' \
+              -i $SRC/bootstrap.toml
+            printf "\e[031mShared library missing, not using system rust to bootstrap.\033[0m\n"
+        fi
+    else
+        sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
+    fi
+
+    if prt-get isinst clang; then
+        sed -e 's|@TARGETCC@|"clang"|g' \
+          -e 's|@TARGETCXX@|"clang++"|g' \
+          -e 's|@TARGETAR@|"llvm-ar"|g' \
+          -e 's|@TARGETRANLIB@|"llvm-ranlib"|g' \
+          -i $SRC/bootstrap.toml
+    else
+        sed -e 's|@TARGETCC@|"gcc"|g' \
+          -e 's|@TARGETCXX@|"g++"|g' \
+          -e 's|@TARGETAR@|"gcc-ar"|g' \
+          -e 's|@TARGETRANLIB@|"gcc-ranlib"|g' \
+          -i $SRC/bootstrap.toml
+    fi
 
     cat $SRC/bootstrap.toml
 
@@ -155,16 +188,13 @@ EOF
     #   --> src/bootstrap/lib.rs:280:5
     #   = note: `-D dead-code` implied by `-D warnings`
     export RUSTFLAGS+=' -A dead_code'
-    export RUSTFLAGS+=' -C link-arg=-fuse-ld=bfd'
 
     unset CFLAGS CXXFLAGS
 
     { [ ! -e /usr/include/libssh2.h ] ||
         export LIBSSH2_SYS_USE_PKG_CONFIG=1; }
     export RUST_BACKTRACE=full
-    LIBGCC_DIR="$(dirname "$(gcc -print-libgcc-file-name)")"
-    /usr/bin/python3 ./x.py build --config="${SRC}"/bootstrap.toml -j ${JOBS-1}
-    DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/bootstrap.toml install
+    DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/bootstrap.toml install -j $(nproc)
 
     prt-get isinst bash-completion || rm -r $PKG/usr/share/bash-completion
     prt-get isinst zsh || rm -r $PKG/usr/share/zsh
